select * from USERPROFILE;
select * FROM COUNTRY;
select * FROM TASK;
SELECT * FROM CITY;
SELECT * FROM TODO_LIST;
SELECT * FROM CATEGORY;
SELECT a.id FROM ACHIEVEMENT AS a INNER JOIN USER_ACHIEVEMENT AS ua ON ua.user_fk = 100 WHERE ua.achievement_fk = a.id;